























































































































































































































































































































































































</style>}  font-size: 14px;  color: var(--color-text-3);.group-stats {}  margin-bottom: 8px;  font-weight: 500;  font-size: 18px;.group-name {}  flex: 1;.group-info {}  color: var(--color-primary);.group-icon {}  padding: 16px;  gap: 16px;  align-items: center;  display: flex;  height: 100%;.group-card-content {}  color: var(--color-primary);.add-group:hover .add-group-content {}  color: var(--color-text-3);  gap: 12px;  align-items: center;  justify-content: center;  flex-direction: column;  display: flex;  height: 100%;.add-group-content {}  background-color: var(--color-fill-3);  border-color: var(--color-primary);.add-group:hover {}  background-color: var(--color-fill-2);  border: 2px dashed var(--color-neutral-3);.add-group {}  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);  transform: translateY(-4px);.group-card:hover {}  transition: all 0.3s;  height: 160px;.group-card {}  padding: 16px;  gap: 24px;  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));  display: grid;.groups-grid {}  padding: 0 16px;  margin-bottom: 24px;  align-items: center;  justify-content: space-between;  display: flex;.page-header {<style scoped></script>});  loadGroups();onMounted(() => {};  return "0";  // TODO: 实现获取分组卡片数量的逻辑const getGroupCardCount = (group: string) => {// 获取分组中的卡片数量（可以通过接口获取或者缓存）};  });    params: { group: encodeURIComponent(group) },    name: "groupDetail",  router.push({const goToGroupDetail = (group: string) => {const router = useRouter();// 跳转到分组详情页面};  loadCards(currentGroup.value);  currentPage.value = 1; // 重置到第一页  pageSize.value = size;const handlePageSizeChange = (size: number) => {// 添加每页条数改变的处理方法};  loadCards(currentGroup.value);  currentPage.value = page;const handlePageChange = (page: number) => {// 添加页码改变的处理方法};  return content.length > 50 ? content.slice(0, 50) + "..." : content;  if (!content) return "";const truncateContent = (content: string | undefined) => {// 内容预览截断};  }    syncLoading.value = false;  } finally {    Message.error("同步失败");  } catch (error) {    }      Message.success("同步成功");    if (res.code === 200) {    const res = await CardControllerService.syncWithAnki();  try {  syncLoading.value = true;const syncWithAnki = async () => {// 同步到Anki};  }    Message.error("删除失败");  } catch (error) {    }      loadCards(currentGroup.value);      Message.success("删除成功");    if (res.code === 200) {    const res = await CardControllerService.deleteCard(card.id);  try {const deleteCard = async (card: any) => {// 删除卡片};  }    Message.error(isEditingCard.value ? "更新失败" : "创建失败");  } catch (error) {    }      }        loadCards(currentGroup.value);        cardModalVisible.value = false;        Message.success("创建成功");      if (res.code === 200) {      const res = await CardControllerService.createCard(addParams);      };        group: currentGroup.value,        answer: cardForm.value.answer,        question: cardForm.value.question,      const addParams: CardAddRequest = {      // 创建卡片    } else {      }        loadCards(currentGroup.value);        cardModalVisible.value = false;        Message.success("更新成功");      if (res.code === 200) {      const res = await CardControllerService.updateCard(updateParams);      };        group: currentGroup.value,        answer: cardForm.value.answer,        question: cardForm.value.question,        id: cardForm.value.id,      const updateParams: CardUpdateRequest = {      // 更新卡片    if (isEditingCard.value) {  try {  }    return;    Message.warning("请填写完整信息");  if (!cardForm.value.question.trim() || !cardForm.value.answer.trim()) {const handleCardSubmit = async () => {// 提交卡片表单};  cardModalVisible.value = true;  cardForm.value = { ...card };  cardModalTitle.value = "编辑卡片";  isEditingCard.value = true;const editCard = (card: Card) => {// 编辑卡片};  cardModalVisible.value = true;  };    group: "",    answer: "",    question: "",    id: "",  cardForm.value = {  cardModalTitle.value = "新建卡片";  isEditingCard.value = false;const showAddCard = () => {// 显示新建卡片对话框};  }    Message.error("创建失败");  } catch (error) {    }      loadGroups();      groupModalVisible.value = false;      Message.success("创建成功");    if (res.code === 200) {    const res = await GroupControllerService.addGroup(newGroupName.value);  try {  }    return;    Message.warning("请输入分组名称");  if (!newGroupName.value.trim()) {const handleGroupSubmit = async () => {// 提交新建分组};  groupModalVisible.value = true;  newGroupName.value = "";const showAddGroup = () => {// 显示新建分组对话框};  loadCards(group);  currentGroup.value = group;const selectGroup = (group: string) => {// 选择分组};  }    cardsLoading.value = false;  } finally {    Message.error("加载卡片失败");  } catch (error) {    }      total.value = res.data.totalElements;      cards.value = res.data.content;    if (res.code === 200 && res.data) {    );      pageSize.value      currentPage.value - 1, // 后端从0开始计数      group,    const res = await CardControllerService.getUserGroupCardsWithPagination(  try {  cardsLoading.value = true;  if (!group) return;const loadCards = async (group: string) => {// 修改加载卡片列表的方法};  }    Message.error("加载分组失败");  } catch (error) {    }      groups.value = res.data;    if (res.code === 200 && res.data) {    const res = await GroupControllerService.getUserGroups();  try {const loadGroups = async () => {// 加载分组列表const total = ref(0);const pageSize = ref(12); // 每页显示12张卡片，适合网格布局const currentPage = ref(1);// 添加分页相关的状态const isEditingCard = ref(false);});  group: "",  answer: "",  question: "",  id: "",const cardForm = ref<Card>({const newGroupName = ref("");const groupModalVisible = ref(false);const cardModalTitle = ref("新建卡片");const cardModalVisible = ref(false);// 模态框状态const syncLoading = ref(false);const cardsLoading = ref(false);const currentGroup = ref<string>("");const cards = ref<Card[]>([]);const groups = ref<string[]>([]);// 状态变量}  group?: string;  answer: string;  question: string;  id: string;interface Card {// 接口定义import { useRouter } from "vue-router";import type { CardUpdateRequest } from "../../../generated/models/CardUpdateRequest";import type { CardAddRequest } from "../../../generated/models/CardAddRequest";import { GroupControllerService } from "../../../generated/services/GroupControllerService";import { CardControllerService } from "../../../generated/services/CardControllerService";import { Message } from "@arco-design/web-vue";} from "@arco-design/web-vue/es/icon";  IconMessage,  IconFile,  IconSync,  IconDelete,  IconEdit,  IconFolder,  IconPlus,import {import { ref, onMounted } from "vue";<script setup lang="ts"></template>  </div>    </a-modal>      </a-form>        </a-form-item>          <a-input v-model="newGroupName" placeholder="请输入分组名称" />        <a-form-item field="name" label="分组名称">      <a-form :model="{ name: newGroupName }">    >      @cancel="groupModalVisible = false"      @ok="handleGroupSubmit"      title="新建分组"      v-model:visible="groupModalVisible"    <a-modal    <!-- 新建分组对话框 -->    </div>      </a-card>        </div>          </div>            <div class="group-name">{{ group }}</div>          <div class="group-info">          </div>            <icon-folder :style="{ fontSize: '32px' }" />          <div class="group-icon">        <div class="group-card-content">      >        @click="goToGroupDetail(group)"        hoverable        class="group-card"        :key="group"        v-for="group in groups"      <a-card      <!-- 分组卡片列表 -->      <!--      </a-card>-->      <!--        </div>-->      <!--          <span>新建分组</span>-->      <!--          <icon-plus :style="{ fontSize: '32px' }" />-->      <!--        <div class="add-group-content">-->      <!--      <a-card class="group-card add-group" hoverable @click="showAddGroup">-->      <!-- 新建分组卡片 -->    <div class="groups-grid">    </div>      </a-button>        新建分组        </template>          <icon-plus />        <template #icon>      <a-button type="primary" @click="showAddGroup">      <h2>我的分组</h2>    <div class="page-header">  <div id="workspaceView"><template>